#!/usr/bin/perl

#use Getopt::Long;
#use Mysql;

#use Env qw(LSBUSER LSBDBPASSWD LSBDB LSBDBHOST);

sub usage()
{
print STDERR "fixc++spec\n";
die;
}

# Uncomment to trace SQL statments
#$trace=1;

#
# 1) process the arguments
#
#GetOptions("l=s" => \$libname,
#	   "a=s" => \$archname);

#if( !$libname ) { usage(); }
#if( !$archname ) { usage(); }

sub
dotable()
{
#
# Skip down to the next TITLE
#
while(<>) {
	if(/<TITLE>/) {
		$title=$_;
		$title=~/<TITLE>(.+)<\/TITLE>/;
		$title=$1;
		$title=~s/std:://g;
		$title=~s/\</&lt;/g;
		print "<TITLE>$title</TITLE>\n";
		last;
		}
	if(/<\/SECT2>/) {
		#fail-safe for an empty section
		print $_;
		return;
		}
	print $_;
	}
#
# Process each Row in the table
#
while(<>) {
	if(/<\/TABLE>/) {
		#print STDERR $_;
		print $_;
		last;
		}
	if(/<TBODY>/) {
		print $_;
		#print STDERR $_;
		next;
		}
	if(/<\/TBODY>/) {
		#print STDERR $_;
		print $_;
		next;
		}
	if(/<TGROUP/) {
		print $_;
		#print STDERR $_;
		next;
		}
	if(/<\/TGROUP/) {
		print $_;
		#print STDERR $_;
		next;
		}
	if(/<ROW>/) {
		print $_;
		#print STDERR $_;
		next;
		}
	if(/<\/ROW>/) {
		print $_;
		#print STDERR $_;
		next;
		}
	#
	# Process each entry in the table
	#
	if(/<ENTRY>/) {
		#print STDERR "<ENTRY>\n";
		$footnote="";
		$entry=$_;
		$entry=~s/std:://g;
		$entry=~/<ENTRY>(.+)<\/ENTRY>/;
		#print STDERR "Entry: $1\n";
		$entry=$1;
		#$entry=~s/$group\:\://;
		if(/FOOTNOTEREF/) {
			#print STDERR "Found a FOOTNOTEREF\n";
			$footnote=$entry;
			$footnote=~/(.+)<FOOTNOTEREF(.+)>/;
			$entry=$1;
			$footnote=$2;
			}
		$entry=~s/\</&lt;/g;
		$entry=~s/\[/&lsqb;/g;
		print "<ENTRY>$entry";
		if( $footnote ne "" ) {
			print "<FOOTNOTEREF $footnote>";
			}
		print "</ENTRY>\n";
		next;
		}
	print "<!--huh??-->".$_;
	}
}

while(<>) {
	#
	# Top level loop that looks for the tables on which to work.
	#
	s/std:://g;
	if(/<!--libgroup-->/) {
		$title=<>;
		$title=~s/std:://g;
		$group=$title;
		$group=~/<TITLE>(.+)<\/TITLE>/;
		#print STDERR "Title: $title\n";
		#print STDERR "Group: $1\n";
		$group=$1;
		$title=$1;
		$title=~s/\</&lt;/g;
		print "<TITLE>$title</TITLE>\n";
		dotable();
		next;
	}
	if(/<!--libgroupdata-->/) {
		dotable();
		next;
	}
	#s/\</&lt;/g;
	print $_;
}

