#!/usr/bin/perl

use Getopt::Long;
use DBI;

use Env qw(LSBUSER LSBDBPASSWD LSBDB LSBDBHOST);

sub usage()
{
print STDERR "mkdyntagtable -a <archname> -s <stdname> -v lsbversion [-c <numcols>] [-d]\n";
die;
}

# Uncomment to trace SQL statments
#$trace=1;

#
# 1) process the arguments
#
$numcols=1;
$dodesc=0;
GetOptions("a=s" => \$archname,
	   "s=s" => \$stdname,
	   "c=i" => \$numcols,
	   "v=s" => \$lsbversion,
	   "d" => \$dodesc);

if( !$archname ) { usage(); }
if( !$stdname ) { usage(); }
if( !$lsbversion ) { usage(); }

#
# 2) Establish connection to the database
#
my $dbh = DBI->connect('DBI:mysql:database='.$LSBDB.';host='.$LSBDBHOST, $LSBUSER, $LSBDBPASSWD)
    or die "Couldn't connect to database: ".DBI->errstr;

#
# 3) get & print the architecture info
#
$select = "SELECT * FROM Architecture WHERE ";
$select.= "Architecture.Aname=".$dbh->quote($archname);
print STDERR $select,"\n" if $trace;
$sth = $dbh->prepare($select) or die "Couldn't prepare $select query: ".DBI->errstr;
$sth->execute or die "Couldn't execute $select query: ".DBI->errstr;

$entry=$sth->fetchrow_hashref or die "Fetchrow failed on $select query: ".DBI->errstr;
$Aid=$entry->{'Aid'};
$Aname=$entry->{'Aname'};
$sth->finish;

if( not $Aname ) {
	die "Unsupported architecture";
}

$select = "SELECT DEname,ADEdescription ";
$select.= "FROM DynamicEntries ";
$select.= "LEFT JOIN ArchDE ON ADEdeid=DEid ";
$select.= "LEFT JOIN Standard ON ADEstd=Sid ";
$select.= "WHERE Sname=".$dbh->quote($stdname)." ";
$select.= "AND ADEaid=$Aid ";
$select.= "AND (ADEappearedin <= '$lsbversion' and ADEappearedin<>'') ";
$select.= "AND (ADEwithdrawnin IS NULL OR ADEwithdrawnin > '$lsbversion')";
$select.= " ORDER BY DynamicEntries.DEname ";
print STDERR $select,"\n" if $trace;
$sth = $dbh->prepare($select) or die "Couldn't prepare $select query: ".DBI->errstr;
$sth->execute or die "Couldn't execute $select query: ".DBI->errstr;

printf("<!-- Start of generated text - do not edit! -->\n");
printf("<!-- generated from the LSB specification database by mkdyntagtable -->\n");

if($sth->rows) {
	print "<VARIABLELIST>\n";
	for(1..$sth->rows) {
		print "<VARLISTENTRY>\n";
		$entry=$sth->fetchrow_hashref or die "Fetchrow failed on $select query: ".DBI->errstr;
		printf "<TERM>%s</TERM>\n",$entry->{'DEname'};
		printf "<LISTITEM><PARA>%s</PARA></LISTITEM>\n",$entry->{'ADEdescription'};
		print "</VARLISTENTRY>\n";
	}
print "</VARIABLELIST>\n";
}
printf("<!-- End of text generated from database -->\n");

$sth->finish;
$dbh->disconnect;
