#!/usr/bin/perl

use Getopt::Long;
use Mysql;

use Env qw(LSBUSER LSBDBPASSWD LSBDB LSBDBHOST);

sub usage()
{
print STDERR "mkdyntagtable -a <archname> -s <stdname> -v lsbversion [-c <numcols>] [-d]\n";
die;
}

# Uncomment to trace SQL statments
#$trace=1;

#
# 1) process the arguments
#
$numcols=1;
$dodesc=0;
GetOptions("a=s" => \$archname,
	   "s=s" => \$stdname,
	   "c=i" => \$numcols,
	   "v=s" => \$lsbversion,
	   "d" => \$dodesc);

if( !$archname ) { usage(); }
if( !$stdname ) { usage(); }
if( !$lsbversion ) { usage(); }

#
# 2) Establish connection to the database
#
$Dbh = Mysql->connect($LSBDBHOST,$LSBDB,$LSBUSER, $LSBDBPASSWD) || die $Mysql::db_errstr;

#
# 3) get & print the architecture info
#
$select = "SELECT * FROM Architecture WHERE ";
$select.= "Architecture.Aname=".$Dbh->quote($archname);
print STDERR $select,"\n" if $trace;
$sth = $Dbh->query($select) || die $select."\n".$Dbh->errmsg();

%entry=$sth->fetchhash;
$Aid=$entry{'Aid'};
$Aname=$entry{'Aname'};

if( not $Aname ) {
	die "Unsupported architecture";
}

$select = "SELECT DEname,ADEdescription ";
$select.= "FROM DynamicEntries ";
$select.= "LEFT JOIN ArchDE ON ADEdeid=DEid ";
$select.= "LEFT JOIN Standard ON ADEstd=Sid ";
$select.= "WHERE Sname=".$Dbh->quote($stdname)." ";
$select.= "AND ADEaid=$Aid ";
$select.= "AND (ADEappearedin <= '$lsbversion' and ADEappearedin<>'') ";
$select.= "AND (ADEwithdrawnin IS NULL OR ADEwithdrawnin > '$lsbversion')";
$select.= " ORDER BY DynamicEntries.DEname ";
# print $select,"\n";
$sth = $Dbh->query($select) || die $Dbh->errmsg();

printf("<!-- Start of text generated from database -->\n");
printf("<!-- generated from the LSB specification database -->\n");
printf("<!--    by \$Header: mkdyntagtable 1.6 2002/11/26 03:12:51 anderson Exp $- -->\n");
my $now_string = localtime;
printf("<!--    at %s -->\n", $now_string );

if($sth->numrows) {
	print "<VARIABLELIST>\n";
	for(1..$sth->numrows) {
		print "<VARLISTENTRY>\n";
		%entry=$sth->fetchhash;
		printf "<TERM>%s</TERM>\n",$entry{'DEname'};
		printf "<LISTITEM><PARA>%s</PARA></LISTITEM>\n",$entry{'ADEdescription'};
		print "</VARLISTENTRY>\n";
	}
print "</VARIABLELIST>\n";
}
printf("<!-- End of text generated from database -->\n");
printf("<!--    by \$Header: mkdyntagtable 1.6 2002/11/26 03:12:51 anderson Exp $- -->\n");
