#!/usr/bin/perl

use Getopt::Long;
use Mysql;

use Env qw(LSBUSER LSBDBPASSWD LSBDB LSBDBHOST);

sub usage()
{
print STDERR "mkintlist -a <archname> -v <lsbversion>\n";
die;
}

# Uncomment to trace SQL statments
#$trace=1;

#
# 1) process the arguments
#
GetOptions("a=s" => \$archname,
			"v=s" => \$lsbversion);

if( !$archname ) { usage(); }
if( !$lsbversion ) { usage(); }

#
# 2) Establish connection to the database
#
$Dbh = Mysql->connect($LSBDBHOST,$LSBDB,$LSBUSER, $LSBDBPASSWD) || die $Mysql::db_errstr;

#
# 3) get & print the architecture info
#
$select = "SELECT * FROM Architecture WHERE ";
$select.= "Architecture.Aname=".$Dbh->quote($archname);
print STDERR $select,"\n" if $trace;
$sth = $Dbh->query($select) || die $select."\n".$Dbh->errmsg();

%entry=$sth->fetchhash;
$Aid=$entry{'Aid'};
$Aname=$entry{'Aname'};

#print "<APPENDIX ID=app-A>\n";
#print "<TITLE>Alphabetical Listing of Interfaces</TITLE>\n";
#print "<PARA>\n";
#print "</PARA>\n";
#
# 4) get & print the library info
#
$select = "SELECT * FROM Library LEFT JOIN ArchLib ON ALlid=Lid WHERE ";
$select.= "(ALappearedin <= '$lsbversion' AND ALappearedin<>'' ";
$select.= "AND (ALwithdrawnin IS NULL OR ALwithdrawnin > '$lsbversion') ) ";
$select.= "AND ALaid=$Aid ";
print STDERR $select,"\n" if $trace;
$lth = $Dbh->query($select) || die $select."\n".$Dbh->errmsg();
for(1..$lth->numrows) {

%entry=$lth->fetchhash;
$Lid=$entry{'Lid'};
$Lname=$entry{'Lname'};

$select = "SELECT Iname,Istandard,Isrcbin,Ideprecatedsince,Vname ";
#$select.= "FROM Interface,LGInt,LibGroup ";
$select.= "FROM Interface ";
$select.= "INNER JOIN LGInt ON LGIint=Iid ";
$select.= "INNER JOIN LibGroup ON LGlib=$Lid ";
$select.= "LEFT JOIN ArchInt ON Iid=AIint ";
$select.= "LEFT JOIN Version ON Vid=AIversion ";
#$select.= "WHERE Iid=LGIint AND LGIlibg=LGid AND Itype='Function' ";
$select.= "WHERE LGIlibg=LGid AND Itype='Function' ";
#$select.= "AND LGlib=$Lid AND Iarch=$Aid ";
$select.= "AND AIarch=$Aid ";
$select.= "AND (AIappearedin <= '$lsbversion' and AIappearedin<>'') ";
$select.= "AND (AIwithdrawnin IS NULL OR AIwithdrawnin >'$lsbversion') ";
# Include only arch specific interfaces
if( $Aid!=1 ) {
	$select.= "AND Iid NOT IN ";
	$select.= "(SELECT Iid FROM Interface";
	$select.= " LEFT JOIN ArchInt ON Iid=AIint";
	$select.= " WHERE AIarch=1 ";
	$select.= "AND (AIappearedin <= '$lsbversion' and AIappearedin<>'') ";
	$select.= "AND (AIwithdrawnin IS NULL OR AIwithdrawnin >'$lsbversion') )";
}
$select.= "ORDER BY Iname";
$inh = $Dbh->query($select) || die $select."\n".$Dbh->errmsg();
if( $inh->numrows == 0) { next; }

print "$Lname Function Interfaces\n";

#
# 7) Get a list of the interfaces in the library
#
{
	local(*std);
	local(*symver);
	local(*entry);
	print STDERR $select,"\n" if $trace;
	for(1..$inh->numrows) {
		%entry=$inh->fetchhash;
		print $entry{'Iname'}."(".$entry{'Vname'}.")";
		if( $entry{'Ideprecatedsince'} and $entry{'Ideprecatedsince'} le $lsbversion ) {
			print " *Deprecated*";
			}
		print "\n";
	}
}

#
# 8) Make a table of data interfaces
#
{
	local(*datasym);
	local(*std);

	$select = "SELECT * FROM Interface ";
	$select.= "LEFT JOIN LGInt ON Iid=LGIint ";
	$select.= "LEFT JOIN LibGroup ON LGIlibg=LGid ";
	$select.= "LEFT JOIN ArchInt ON Iid=AIint ";
	$select.= "WHERE Itype='Data' AND LGlib=$Lid AND AIarch=$Aid ";
	$select.= "AND (AIappearedin <= '$lsbversion' and AIappearedin<>'') ";
	$select.= "AND (AIwithdrawnin IS NULL OR AIwithdrawnin >'$lsbversion') ";
	if( $Aid!=1 ) {
		$select.= "AND Iid NOT IN ";
		$select.= "(SELECT Iid FROM Interface";
		$select.= " LEFT JOIN ArchInt ON Iid=AIint";
		$select.= " WHERE AIarch=1 ";
		$select.= "AND (AIappearedin <= '$lsbversion' and AIappearedin<>'') ";
		$select.= "AND (AIwithdrawnin IS NULL OR AIwithdrawnin >'$lsbversion') ) ";
	}
	$select.= "ORDER BY Iname";
		
	print STDERR $select,"\n" if $trace;
	$sth = $Dbh->query($select) || die $select."\n".$Dbh->errmsg();
	if ($sth->numrows > 0 ) {
	print "$Lname Data Interfaces\n";
		for(1..$sth->numrows) {
			%datasym=$sth->fetchhash;
			print $datasym{'Iname'}."(".$datasym{'Vname'}.")\n";
		}
	}
}
}
