#!/usr/bin/perl

use Getopt::Long;
use POSIX qw(strftime);

sub usage()
{
print STDERR "mkmanpage -n <name>\n";
die;
}

#
# 1) process the arguments
#
GetOptions("n=s" => \$manname);

if( !$manname ) { usage(); }

$date = strftime "%e %b %Y", gmtime();
print "<REFENTRY ID=\"".$manname."-1\"> <REFMETA>
<REFENTRYTITLE>".$manname."</REFENTRYTITLE>
<REFMISCINFO>What Section??</REFMISCINFO>
</REFMETA>
<REFNAMEDIV>
<REFNAME>".$manname;
print "</REFNAME>
<REFPURPOSE>What is this?
</REFPURPOSE>
</REFNAMEDIV>
<REFSYNOPSISDIV>
<REFSYNOPSISDIVINFO>
<DATE>".$date."</DATE>
</REFSYNOPSISDIVINFO>
<SYNOPSIS>";
print "return_type ".$manname."(parameters)";
print " </SYNOPSIS>
</REFSYNOPSISDIV>
<REFSECT1>
<REFSECT1INFO>
<DATE>".$date."</DATE>
</REFSECT1INFO>
<TITLE>Description
</TITLE>
<PARA>
</PARA>
</REFSECT1>
</REFENTRY>";
