#!/usr/local/bin/perl

use CGI;
use Carp;
use Mysql;

$query = new CGI(%ARGV);

$Dbh = Mysql->connect(localhost) || die $Mysql::db_errstr;
$Dbh->selectdb("Linux") || die $Dbh->errmsg();

$select  ="SELECT DISTINCT Interface.Iname ";
$select .="FROM Standard,Interface,StandInt";

if ( $query->param('Sname') ) {
	push(@where,"Standard.Sname=".$Dbh->quote($query->param('Sname')));
	push(@where,"Standard.Sid=StandInt.SIstand");
	push(@where,"Interface.Iid=StandInt.SIint");
}

push(@where,"Interface.Iname NOT LIKE '\\_\\_%'");

if( scalar(@where) > 0 ) {
	$select .= " WHERE ".join(" AND ",@where);
	}
$select .=" ORDER BY Interface.Iname ";
#printf $select,"\n";
$sth = $Dbh->query($select) || die $select."\n".$Dbh->errmsg();

for(1..$sth->numrows) {
	%entry=$sth->fetchhash;
	$entry[$_]=$entry{'Iname'};
}

print "<HTML>\n";
print "<BODY>\n";
print "<TABLE>\n";
$inc=($sth->numrows+4)/5;
for(1..$inc) {
	print "<TR>";
	printf "<TD>%s</TD>",$entry[$_];
	printf "<TD>%s</TD>",$entry[$_+$inc];
	printf "<TD>%s</TD>",$entry[$_+(2*$inc)];
	printf "<TD>%s</TD>",$entry[$_+(3*$inc)];
	printf "<TD>%s</TD>",$entry[$_+(4*$inc)];
	print "</TR>\n";
}
print "</TABLE>\n";
print "</BODY>\n";
print "</HTML>\n";
