#!/usr/bin/perl

use CGI;
use Carp;
use Mysql;

use Env qw(LSBUSER LSBDBPASSWD LSBDB LSBDBHOST);

$query = new CGI(%ARGV);

$Dbh = Mysql->connect($LSBDBHOST,$LSBDB,$LSBUSER, $LSBDBPASSWD) || die $Mysql::db_errstr;

$select  ="SELECT DISTINCT Interface.Iname ";
$select .="FROM Standard,Interface,StandInt";

if ( $query->param('Sname') ) {
	push(@where,"Standard.Sname=".$Dbh->quote($query->param('Sname')));
	push(@where,"Standard.Sid=StandInt.SIstand");
	push(@where,"Interface.Iid=StandInt.SIint");
}

push(@where,"Interface.Iname NOT LIKE '\\_\\_%'");

if( scalar(@where) > 0 ) {
	$select .= " WHERE ".join(" AND ",@where);
	}
$select .=" ORDER BY Interface.Iname ";
#printf $select,"\n";
$sth = $Dbh->query($select) || die $select."\n".$Dbh->errmsg();

for(1..$sth->numrows) {
	%entry=$sth->fetchhash;
	$entry[$_]=$entry{'Iname'};
}

print "<html>\n";
print "<body>\n";
print "<table>\n";
$inc=($sth->numrows+4)/5;
for(1..$inc) {
	print "<tr>";
	printf "<td>%s</td>",$entry[$_];
	printf "<td>%s</td>",$entry[$_+$inc];
	printf "<td>%s</td>",$entry[$_+(2*$inc)];
	printf "<td>%s</td>",$entry[$_+(3*$inc)];
	printf "<td>%s</td>",$entry[$_+(4*$inc)];
	print "</tr>\n";
}
print "</table>\n";
print "</body>\n";
print "</html>\n";
