#!/usr/bin/perl
#
#	Linux Standard Base, http://www.linuxbase.org/
#	George Kraft IV, gk4@us.ibm.com, 03/09/2000
#
#


use DBI;
use Env qw(LSBUSER LSBDBPASSWD LSBDB LSBDBHOST);

local %references;
local %standards;

################################################################################
#	lsbOpenDB
################################################################################

sub lsbOpenDB {

	$dbh = DBI->connect("DBI:mysql:$LSBDB", $LSBUSER, $LSBDBPASSWD);
	die unless $dbh;

	$sth = $dbh->prepare( "SHOW TABLES" );
	$sth->execute;

}

################################################################################
#	lsbCloseDB
################################################################################

sub lsbCloseDB {

	$sth = $dbh->prepare( "SHOW TABLES" );
	$sth->execute;

	$sth->finish;
	$dbh->disconnect;
}

################################################################################
#	lsbCommands
################################################################################

sub lsbCommands {

		$sth = $dbh->prepare("SELECT DISTINCT Interface.Iname, Standard.Sid, Standard.Sfull FROM Interface left join StandUgInt on Interface.Iid=StandUgInt.UGIint, Standard WHERE StandUgInt.UGIstand=Standard.Sid AND StandUgInt.UGIlsb='1' ORDER BY Interface.Iname");
		$sth->execute;

		if ($sth->rows < 1) {
			printf("No Commands or Utilities found!\n");
			return;
		} 

		printf("<para>\n");
		printf("The behaviour of the interfaces described in this\n");
		printf("section are specified by the following Standards.");
		printf("</para>\n");
		printf("<simplelist columns=1>\n");

		my $i = 0;
		while (@field = $sth->fetchrow_array) {
			if (!$standards{$field[1]}) {
				++$i;
				$standards{$field[1]} = $field[2];
				$references{$i} = $field[1];
				$permutation{$field[1]} = $i;
				$ref = $i;
			} else {
				$ref = $permutation{$field[1]};
			}

			$ftid = sprintf("std-ugi-fn-%s-%s",  
				$field[1], $permutation{$field[1]});

			if (!$footer{$ftid}) {
				$footer{$ftid} = $ref;
				printf("<member>%s\n", $standards{$field[1]});
				printf("<footnote id=\"%s\">\n", $ftid);
				printf("<para>%s</para></footnote>", 
					$standards{$field[1]});
				printf("</member>\n");
			}
		}
		printf("</simplelist>\n");

		$sth = $dbh->prepare("SELECT DISTINCT Interface.Iname, Standard.Sid, Standard.Sfull FROM Interface left join StandUgInt on Interface.Iid=StandUgInt.UGIint, Standard WHERE StandUgInt.UGIstand=Standard.Sid AND StandUgInt.UGIlsb='1' ORDER BY Interface.Iname");
		$sth->execute;

		if ($sth->rows < 1) {
			printf("No Commands or Utilities found!\n");
			return;
		} 

		printf("<table>\n");
		printf("<title></title>\n");
		printf("<tgroup cols=5>\n");
		printf("<tbody>\n");
		printf("<row>\n");

		my $i = 0;
		while (@field = $sth->fetchrow_array) {
			$ref = $permutation{$field[1]};

			if ($i != 0 && 0 == ($i % 5)) {
				printf("</row><row>\n");
			}

			$ftid = sprintf("std-ugi-fn-%s-%s",  
				$field[1], $permutation{$field[1]});

			printf("<entry>%s\n", $field[0]);
			printf("<footnoteref linkend=\"%s\">\n", $ftid);
			printf("</entry>\n");

			++$i;
		}

		printf("</row>\n");
		printf("</tbody>\n");
		printf("</tgroup>\n");
		printf("</table>\n");

}

################################################################################
#	main
################################################################################

lsbOpenDB;
lsbCommands;
lsbCloseDB;

exit;

# EOF
