#!/usr/local/bin/perl

use Carp;
use Mysql;

$Dbh = Mysql->connect(localhost) || die $Mysql::db_errstr;
$Dbh->selectdb("Linux") || die $Dbh->errmsg();

$select  ="SELECT * ";
$select .="FROM Library WHERE Lstd='Y'";

#$select .=" ORDER BY Lname ";
#printf $select,"\n";
$sth = $Dbh->query($select) || die $Dbh->errmsg();

print "<TBODY>\n";
print "<ROW>\n";
print "<ENTRY>Library</ENTRY>\n";
print "<ENTRY>Runtime Name</ENTRY>\n";
print "</ROW>\n";
for(1..$sth->numrows) {
	%entry=$sth->fetchhash;
	print "<ROW>";
	printf "<ENTRY>%s</ENTRY>",$entry{'Lname'};
	printf "<ENTRY>%s</ENTRY>",$entry{'Lrunname'};
	print "</ROW>\n";
}
print "</TBODY>\n";
