#!/usr/bin/perl

use Carp;
use Mysql;

use Env qw(LSBUSER LSBDBPASSWD LSBDB LSBDBHOST);

$Dbh = Mysql->connect($LSBDBHOST,$LSBDB,$LSBUSER, $LSBDBPASSWD) || die $Mysql::db_errstr;

$select  ="SELECT * ";
$select .="FROM Library WHERE Lstd='Y'";

#$select .=" ORDER BY Lname ";
#printf $select,"\n";
$sth = $Dbh->query($select) || die $Dbh->errmsg();

print "<TBODY>\n";
for(1..$sth->numrows) {
	%entry=$sth->fetchhash;
	print "<ROW>";
	printf "<ENTRY>%s</ENTRY>",$entry{'Lname'};
	printf "<ENTRY>%s</ENTRY>",$entry{'Lrunname'};
	print "</ROW>\n";
}
print "</TBODY>\n";
