#!/usr/bin/perl

use Carp;
use Mysql;

use Env qw(LSBUSER LSBDBPASSWD LSBDB LSBDBHOST);

$Dbh = Mysql->connect($LSBDBHOST,$LSBDB,$LSBUSER,$LSBDBPASSWD) || die $Mysql::db_errstr;

$select = "SELECT * FROM Standard";
#printf $select,"\n";
$sth = $Dbh->query($select) || die $Dbh->errmsg();

print "<TBODY>\n";
for(1..$sth->numrows) {
	%entry=$sth->fetchhash;
	print "<ROW>";
	printf "<ENTRY>%s</ENTRY>",$entry{'Sname'};
	printf "<ENTRY>%s</ENTRY>",$entry{'Sfull'};
	printf "<ENTRY>%s</ENTRY>",$entry{'Surl'};
	printf "<ENTRY>%s</ENTRY>",$entry{'Scomment'};
	print "</ROW>\n";
}
print "</TBODY>\n";
