#!/usr/bin/perl

use CGI;
use Carp;
use Mysql;

use Env qw(LSBUSER LSBDBPASSWD LSBDB LSBDBHOST);

$query = new CGI(%ARGV);

$Dbh = Mysql->connect($LSBDBHOST,$LSBDB,$LSBUSER, $LSBDBPASSWD) || die $Mysql::db_errstr;

if( $query->param('numcols') ) {
	$numcols=$query->param('numcols');
} else {
	$numcols=1;
}
if( $query->param('dodesc') ) {
	$dodesc=$query->param('dodesc');
} else {
	$dodesc='N';
}
$select  ="SELECT DEname,DEdescription ";
$select .="FROM DynamicEntries,Standard ";
$select .="WHERE DEstandard=Sid and Sname=".$Dbh->quote($query->param('Sname'));

$select .=" ORDER BY DynamicEntries.DEname ";
#print $select,"\n";
$sth = $Dbh->query($select) || die $Dbh->errmsg();

print "<TBODY>\n";
print "<ROW>";
$curcol=1;
for(1..$sth->numrows) {
	%entry=$sth->fetchhash;
	printf "<ENTRY>%s</ENTRY>",$entry{'DEname'};
	if ( $dodesc eq 'Y' ) {
		printf "<ENTRY>%s</ENTRY>",$entry{'DEdescription'};
	}
	if( $curcol%$numcols == 0 && $_ != $sth->numrows) {
		print "</ROW>\n";
		print "<ROW>";
		$curcol=1;
	} else {
		$curcol++;
	}
}
print "</ROW>\n";
print "</TBODY>\n";
